package ru.otus.entities;

import jakarta.validation.constraints.NotNull;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.annotation.Transient;
import org.springframework.data.domain.Persistable;
import org.springframework.data.relational.core.mapping.Table;

@Data
@Table("CATEGORIES_WITHOUT_AUTOGENERATED_ID")
public class CategoryWithoutAutogeneratedId implements Persistable<Long> {
    @Id
    @NotNull(message = "Category ID cannot be empty")
    private Long id;
    @NotNull(message = "Category name cannot be empty")
    private String title;
    @Transient
    private boolean isNew;

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PersistenceCreator
    public CategoryWithoutAutogeneratedId(Long id, String title) {
        this.id = id;
        this.title = title;
    }
}